// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Univercity_objects.Infrastructure;

#nullable disable

namespace Univercity_objects.Infrastructure.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Univercity_objects.Domain.BaseEntity", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inv_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("guid");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Univercity_objects.Domain.CafedraEntity", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("guid");

                    b.ToTable("CafedraEntities");
                });

            modelBuilder.Entity("Univercity_objects.Domain.Auditory", b =>
                {
                    b.HasBaseType("Univercity_objects.Domain.BaseEntity");

                    b.Property<Guid>("cafedraguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("cafedraguid");

                    b.ToTable("Auditories");
                });

            modelBuilder.Entity("Univercity_objects.Domain.AuditoryComponentEntity", b =>
                {
                    b.HasBaseType("Univercity_objects.Domain.BaseEntity");

                    b.Property<Guid>("Auditoryguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Auditoryguid");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Univercity_objects.Domain.ComputerEntity", b =>
                {
                    b.HasBaseType("Univercity_objects.Domain.AuditoryComponentEntity");

                    b.Property<string>("specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ComputerEntities");
                });

            modelBuilder.Entity("Univercity_objects.Domain.FurnitureEntity", b =>
                {
                    b.HasBaseType("Univercity_objects.Domain.AuditoryComponentEntity");

                    b.ToTable("FurnitureEntities");
                });

            modelBuilder.Entity("Univercity_objects.Domain.MultimediaEqumentEntity", b =>
                {
                    b.HasBaseType("Univercity_objects.Domain.AuditoryComponentEntity");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MultimediaEqumentEntities");
                });

            modelBuilder.Entity("Univercity_objects.Domain.Auditory", b =>
                {
                    b.HasOne("Univercity_objects.Domain.CafedraEntity", "cafedra")
                        .WithMany()
                        .HasForeignKey("cafedraguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cafedra");
                });

            modelBuilder.Entity("Univercity_objects.Domain.AuditoryComponentEntity", b =>
                {
                    b.HasOne("Univercity_objects.Domain.Auditory", "Auditory")
                        .WithMany()
                        .HasForeignKey("Auditoryguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditory");
                });
#pragma warning restore 612, 618
        }
    }
}
